export interface Fish {
  id: string;
  name: string;
  japaneseName: string;
  nameEn: string;
  emoji: string;
  gradientFrom: string;
  gradientTo: string;
  bestMonths: string[];
  tasteScore: number;
  eatingMethod: string;
  sakePairing: string;
  sakeNote: string;
  origin: string;
  description: string;
  flavor: string;
  texture: string;
  category: string;
  difficulty: string;
  calories: number;
  protein: number;
  fat: number;
  imageUrl: string;
  slug: string;
}

export const fishData: Fish[] = [
  { id:'1', name:'金枪鱼大腹', japaneseName:'おおとろ / マグロ大腹', nameEn:'Bluefin Tuna Fatty Belly', emoji:'🐟', gradientFrom:'#FF4E50', gradientTo:'#F9D423', bestMonths:['4月','5月','6月'], tasteScore:4.9, eatingMethod:'刺身、握寿司', sakePairing:'纯米酒', sakeNote:'大腹脂肪丰厚，纯米酒的米香与鲜甜油脂形成绝妙平衡，互相映衬而不压味。', origin:'青森县大间', description:'大腹（Otoro）是金枪鱼腹部最肥厚的部分，脂肪纹路如霜降牛肉般细密。每年春末至初夏，青森大间近海捕获的黑金枪鱼大腹尤为肥美，入口即化，被誉为"寿司之王"。高端寿司店的大腹价格可达普通食材十数倍，是真正的奢华食材。', flavor:'入口即化，满口鲜甜脂香，余味悠长', texture:'极度柔嫩，脂肪分布均匀如霜降', category:'红肉鱼', difficulty:'精深', calories:344, protein:20.1, fat:28.9, imageUrl:'', slug:'otoro' },
  { id:'2', name:'鰤鱼', japaneseName:'ぶり / 鰤', nameEn:'Japanese Amberjack', emoji:'🐠', gradientFrom:'#4776E6', gradientTo:'#8E54E9', bestMonths:['11月','12月','1月'], tasteScore:4.3, eatingMethod:'炙烤、握寿司、刺身', sakePairing:'吟酿酒', sakeNote:'寒鰤油脂丰厚味浓，吟酿的果香与花香可与其丰腴鲜味层次呼应，如双重奏般和谐。', origin:'富山县氷见', description:'鰤鱼是典型的"出世鱼"，日本人依体型不同给予不同名称（モジャコ→ワカシ→イナダ→ワラサ→ブリ），象征成功晋升。冬季严寒时的"寒鰤"脂肪最为肥美，富山氷见产的鰤鱼在日本享有最高声誉，被誉为"冬季鱼王"。', flavor:'油脂丰满，鲜味醇厚，带海洋气息', texture:'肉质饱满，油润厚实', category:'红肉鱼', difficulty:'简单', calories:257, protein:21.4, fat:17.6, imageUrl:'', slug:'buri' },
  { id:'3', name:'樱鲷', japaneseName:'さくらだい / 桜鯛', nameEn:'Cherry Blossom Sea Bream', emoji:'🌸', gradientFrom:'#f953c6', gradientTo:'#b91d73', bestMonths:['3月','4月'], tasteScore:4.0, eatingMethod:'刺身、握寿司、昆布腌', sakePairing:'起泡清酒', sakeNote:'樱鲷春季清甜细腻，起泡清酒的气泡与细腻酸度将其鲜甜完美释放，宛如樱花盛放般明快。', origin:'濑户内海', description:'樱鲷是日本真鲷（マダイ）在3-4月樱花盛开时节的美称。此时真鲷因产卵前大量进食而肥美，鱼皮呈现宛如樱花的粉红色泽，被奉为春季食材中的至宝。', flavor:'清甜鲜嫩，带淡淡昆布风味', texture:'细腻有弹性，脂肪适中', category:'白肉鱼', difficulty:'中等', calories:142, protein:20.9, fat:5.8, imageUrl:'', slug:'sakuradai' },
  { id:'4', name:'鲑鱼', japaneseName:'サーモン / 鮭', nameEn:'Atlantic Salmon', emoji:'🐟', gradientFrom:'#f7971e', gradientTo:'#ffd200', bestMonths:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tasteScore:4.5, eatingMethod:'刺身、握寿司、炙烤', sakePairing:'纯米酒', sakeNote:'鲑鱼橙红色的油脂香气浓郁，与纯米酒的米香饱满口感相辅相成，使整体风味更显圆润。', origin:'挪威 / 智利', description:'养殖大西洋鲑是当今世界消费量最大的寿司食材，其橙红色的漂亮切面和丰富omega-3油脂广受欢迎。炙烤做法（炙りサーモン）近年来极为流行。', flavor:'奶香浓郁，油脂醇厚，微甜', texture:'软嫩多汁，油花细密', category:'红肉鱼', difficulty:'简单', calories:208, protein:20.1, fat:13.6, imageUrl:'', slug:'salmon' },
  { id:'5', name:'海胆', japaneseName:'うに / 雲丹', nameEn:'Sea Urchin (Uni)', emoji:'🦔', gradientFrom:'#F2994A', gradientTo:'#F2C94C', bestMonths:['5月','6月','7月','8月'], tasteScore:4.8, eatingMethod:'军舰卷、刺身丼', sakePairing:'干型纯米大吟酿', sakeNote:'海胆浓郁的矿物感与碘香，需要纯米大吟酿的复杂性与干净余韵来平衡，避免甜味与腥感相撞。', origin:'北海道礼文岛 / 利尻岛', description:'海胆（Uni）是寿司食材中最珍贵的之一，食用的是其生殖腺部分。北海道礼文岛出产的馬糞海胆因昆布丰富的海床而拥有独特的甘甜和浓郁矿物感，被誉为日本最顶级海胆。', flavor:'极度甘甜，浓郁矿物感，碘香海洋气息', texture:'奶油般柔滑，入口即化', category:'贝类', difficulty:'精深', calories:118, protein:13.0, fat:5.0, imageUrl:'', slug:'uni' },
  { id:'6', name:'星鳗', japaneseName:'あなご / 穴子', nameEn:'Conger Eel', emoji:'🐍', gradientFrom:'#2C3E50', gradientTo:'#4CA1AF', bestMonths:['6月','7月','8月'], tasteScore:4.4, eatingMethod:'炙烤握寿司、箱押寿司', sakePairing:'本酿造', sakeNote:'经过师傅秘传汤汁煨煮和炙烤的星鳗风味甜咸浓郁，本酿造清酒的酒精感可清洁口腔，为下一口做好准备。', origin:'东京湾江户川河口', description:'星鳗（Anago）是江户前寿司的标志性食材，与淡水鳗鱼不同，穴子生活于海水中。寿司师傅会以祖传秘制酱汁缓慢煨煮后炙烤，柔软甘甜令人难忘。', flavor:'甘甜浓郁，酱香软糯', texture:'极度软嫩，几乎入口即化', category:'白肉鱼', difficulty:'精深', calories:161, protein:17.3, fat:9.3, imageUrl:'', slug:'anago' },
  { id:'7', name:'鲭鱼', japaneseName:'さば / 鯖', nameEn:'Mackerel', emoji:'🐟', gradientFrom:'#0F9B58', gradientTo:'#00BCD4', bestMonths:['9月','10月','11月'], tasteScore:4.0, eatingMethod:'醋腌刺身、炙烤握寿司', sakePairing:'浊酒', sakeNote:'醋腌鲭鱼酸味与油脂并重，浊酒的乳酸菌风味能与鲭鱼的青背鱼风味形成完美制衡。', origin:'三重县関鯖', description:'鲭鱼是日本最具代表性的青背鱼之一。秋季鲭鱼因积累大量脂肪用于越冬而格外肥美，传统处理方式是以醋腌渍（しめさば），在关西地区的押寿司中尤为经典。', flavor:'鲜味浓郁，酸香开胃，油脂丰富', texture:'肉质厚实，醋腌后略带嚼劲', category:'青背鱼', difficulty:'中等', calories:247, protein:20.7, fat:16.8, imageUrl:'', slug:'saba' },
  { id:'8', name:'竹荚鱼', japaneseName:'あじ / 鯵', nameEn:'Japanese Jack Mackerel', emoji:'🐟', gradientFrom:'#1D976C', gradientTo:'#93F9B9', bestMonths:['5月','6月','7月'], tasteScore:3.9, eatingMethod:'刺身、握寿司、醋腌', sakePairing:'轻快型吟酿', sakeNote:'竹荚鱼初夏时节清甜鲜嫩，轻快型吟酿的淡雅果香能衬托其纤细风味，不至于盖过食材本味。', origin:'大分县関鯵', description:'竹荚鱼被誉为"江户前寿司的平民美味"。大分县速吸濑户的"関鯵"因在湍急海流中成长，肉质格外紧实，是日本认定的品牌鱼之一。', flavor:'清甜鲜嫩，油脂适中，淡淡青草气', texture:'肉质细嫩，弹性适中', category:'青背鱼', difficulty:'简单', calories:126, protein:20.7, fat:4.8, imageUrl:'', slug:'aji' },
  { id:'9', name:'鲣鱼', japaneseName:'かつお / 鰹', nameEn:'Skipjack Tuna', emoji:'🐟', gradientFrom:'#e52d27', gradientTo:'#b31217', bestMonths:['3月','4月','9月','10月'], tasteScore:4.1, eatingMethod:'炙烤握寿司、刺身', sakePairing:'辛口本酿造', sakeNote:'鲣鱼炙烤后焦香扑鼻，辛口本酿造的干爽口感可清洁油脂感，配以姜末和葱花，形成层次丰富的体验。', origin:'高知县土佐', description:'日本有句谚语："初鰹を食わぬ奴は野暮だ"（不吃初鰹的人是土包子）。春季北上的"初鰹"清瘦鲜嫩，秋季南返的"戻り鰹"脂肪丰厚，高知县土佐是著名的炙烤鲣鱼发源地。', flavor:'鲜味浓烈，炙烤后焦香四溢，春秋风味迥异', texture:'肉质紧实，咬劲十足', category:'红肉鱼', difficulty:'中等', calories:165, protein:25.8, fat:6.2, imageUrl:'', slug:'katsuo' },
  { id:'10', name:'秋刀鱼', japaneseName:'さんま / 秋刀魚', nameEn:'Pacific Saury', emoji:'🐟', gradientFrom:'#2b5876', gradientTo:'#4e4376', bestMonths:['9月','10月'], tasteScore:3.8, eatingMethod:'炙烤握寿司、押寿司', sakePairing:'辛口纯米', sakeNote:'秋刀鱼皮下脂肪丰富，辛口纯米的力度可以融合其浓郁风味，同时中和微苦的内脏余韵。', origin:'北海道 / 三陆', description:'秋刀鱼是日本秋季最具代表性的大众美味，炭火炙烤后皮脆肉嫩，香气飘满整个街道，是日本秋季的风物诗。近年因气候变化，秋刀鱼资源量减少，价格已从平民食材升级为时令珍品。', flavor:'脂香浓郁，炙烤焦香，带特有苦甘味', texture:'皮脆肉嫩，油脂丰腴', category:'青背鱼', difficulty:'简单', calories:310, protein:18.5, fat:24.6, imageUrl:'', slug:'sanma' },
  { id:'11', name:'比目鱼', japaneseName:'ひらめ / 平目', nameEn:'Olive Flounder', emoji:'🐡', gradientFrom:'#bdc3c7', gradientTo:'#7f8c8d', bestMonths:['11月','12月','1月','2月'], tasteScore:4.5, eatingMethod:'刺身、握寿司、昆布腌', sakePairing:'干型起泡', sakeNote:'比目鱼冬季白肉极为清淡细腻，干型起泡清酒的矿物感与细腻气泡能轻盈地托起其纤细鲜味，不显突兀。', origin:'青森 / 爱知', description:'比目鱼（Hirame）是日本最顶级的白肉鱼之一，其"缘側"（鳍边肉）尤为珍贵，冬季产卵前脂肪积累充足，此时的"寒ひらめ"被视为白肉鱼中的极品。', flavor:'清淡优雅，回甘细腻，缘側脂香更浓', texture:'细腻弹嫩，几乎无腥味', category:'白肉鱼', difficulty:'精深', calories:95, protein:20.0, fat:2.0, imageUrl:'', slug:'hirame' },
  { id:'12', name:'甘虾', japaneseName:'あまえび / 甘海老', nameEn:'Northern Pink Shrimp', emoji:'🦐', gradientFrom:'#FF8008', gradientTo:'#FFC837', bestMonths:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tasteScore:4.3, eatingMethod:'握寿司（生食）、军舰卷（虾子）', sakePairing:'起泡清酒', sakeNote:'甘虾的名字来源于其天然甜味，起泡清酒的活泼气泡与甘甜鲜味相互映衬，增添欢愉的食用体验。', origin:'北海道 / 富山湾', description:'甘虾以其天然甜味著称，是寿司中极受欢迎的生食食材。甘虾为雌雄同体，雌性甘虾腹部带有虾子（卵），会单独用于军舰卷，更为鲜甜。', flavor:'天然甘甜，鲜味浓郁，入口即化', texture:'极度嫩滑，黏口感十足', category:'虾蟹', difficulty:'简单', calories:87, protein:17.1, fat:1.5, imageUrl:'', slug:'amaebi' },
  { id:'13', name:'扇贝', japaneseName:'ほたて / 帆立貝', nameEn:'Japanese Scallop', emoji:'🐚', gradientFrom:'#E0EAFC', gradientTo:'#CFDEF3', bestMonths:['1月','2月','3月'], tasteScore:4.2, eatingMethod:'握寿司、军舰卷、刺身', sakePairing:'起泡清酒', sakeNote:'扇贝天然甜味浓郁，起泡清酒的清爽气泡感能避免甜味过于厚重，同时引出贝类特有的矿物海鲜香。', origin:'北海道猿払 / 青森陆奥湾', description:'日本帆立贝以北海道猿払产的最为著名，直径可达20cm，被誉为"北方的宝石"。冬季至初春是扇贝积累糖原的最佳时期，此时贝柱天然甜度最高。', flavor:'天然浓甜，带清新海洋矿物感', texture:'柔嫩弹牙，汁水充沛', category:'贝类', difficulty:'简单', calories:72, protein:13.5, fat:0.9, imageUrl:'', slug:'hotate' },
  { id:'14', name:'章鱼', japaneseName:'たこ / 蛸', nameEn:'Octopus', emoji:'🐙', gradientFrom:'#DA22FF', gradientTo:'#9733EE', bestMonths:['6月','7月','8月'], tasteScore:3.9, eatingMethod:'握寿司（水煮）、刺身', sakePairing:'辛口本酿造', sakeNote:'水煮章鱼鲜味纯粹，带轻微嚼劲，辛口本酿造的干爽感能清洁口腔，使嚼劲与酒体形成节奏感的和谐。', origin:'兵库县明石', description:'兵库县明石市是日本最著名的章鱼产地，因急流中生长的章鱼肌肉特别发达，肉质格外弹嫩。章鱼在寿司中通常以水煮后切片使用，是检验寿司职人手艺的标准食材之一。', flavor:'鲜甜淡雅，嚼后鲜味持续释放', texture:'弹嫩有嚼劲，处理得当则不坚韧', category:'软体', difficulty:'中等', calories:70, protein:14.6, fat:0.7, imageUrl:'', slug:'tako' },
  { id:'15', name:'鱿鱼', japaneseName:'いか / 烏賊', nameEn:'Squid', emoji:'🦑', gradientFrom:'#EDDE5D', gradientTo:'#F09819', bestMonths:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tasteScore:3.8, eatingMethod:'刺身、握寿司', sakePairing:'轻柔纯米', sakeNote:'鱿鱼切块后的嫩滑甜味非常纯粹，轻柔纯米酒的淡雅米香能与其清甜相互烘托，不喧宾夺主。', origin:'北海道函馆 / 长崎', description:'乌贼（イカ）在江户前寿司中是经典食材。函馆的真乌贼以夏季最为肥美，现杀的透明鱿鱼切片放在醋饭上，是江户前寿司的特色演出。', flavor:'清甜嫩滑，咬开后鲜汁涌出', texture:'嫩滑中带有独特嚼劲', category:'软体', difficulty:'简单', calories:84, protein:17.9, fat:1.2, imageUrl:'', slug:'ika' },
  { id:'16', name:'真鲷', japaneseName:'まだい / 真鯛', nameEn:'Red Sea Bream', emoji:'🎏', gradientFrom:'#FF416C', gradientTo:'#FF4B2B', bestMonths:['3月','4月','5月'], tasteScore:4.6, eatingMethod:'刺身、握寿司、昆布腌', sakePairing:'大吟酿', sakeNote:'真鲷是白肉鱼中风味最为高雅复杂的，搭配大吟酿的顶级果香与花香，两者皆为"正统高级"的代表，相映成辉。', origin:'兵库县明石 / 爱媛', description:'真鲷（マダイ）在日本拥有"鱼中之王"的崇高地位，在传统文化中象征喜庆吉祥，婚宴和新年料理中不可或缺。昆布腌制是高级寿司店的常见做法，能极大提升鱼肉鲜味。', flavor:'优雅清甜，鲜味高贵，回甘持久', texture:'细腻弹嫩，肌肉纤维清晰', category:'白肉鱼', difficulty:'中等', calories:142, protein:20.6, fat:5.8, imageUrl:'', slug:'madai' },
  { id:'17', name:'鲈鱼', japaneseName:'すずき / 鱸', nameEn:'Japanese Sea Bass', emoji:'🐟', gradientFrom:'#11998e', gradientTo:'#38ef7d', bestMonths:['7月','8月'], tasteScore:4.0, eatingMethod:'刺身、握寿司、皮目炙烤', sakePairing:'辛口纯米', sakeNote:'鲈鱼是夏季出世鱼，白肉清淡而暗藏鲜味，辛口纯米酒的简洁与其低调的鲜味匹配，不引发味觉疲劳。', origin:'东京湾 / 有明海', description:'鲈鱼（スズキ）与鰤鱼同属"出世鱼"，随体型大小依次称为"セイゴ→フッコ→スズキ"。夏季是鲈鱼最肥美的时节，高级寿司店常以皮目轻燎增添烟香层次。', flavor:'清淡雅致，鲜甜中带淡淡烟香', texture:'清爽弹牙，皮下脂肪细腻', category:'白肉鱼', difficulty:'中等', calories:123, protein:19.8, fat:4.2, imageUrl:'', slug:'suzuki' },
  { id:'18', name:'金目鲷', japaneseName:'きんめだい / 金目鯛', nameEn:'Splendid Alfonsino', emoji:'🐠', gradientFrom:'#ED213A', gradientTo:'#93291E', bestMonths:['1月','2月','3月'], tasteScore:4.7, eatingMethod:'刺身、炙烤握寿司', sakePairing:'浓醇纯米酒', sakeNote:'金目鲷皮下脂肪丰厚，炙烤后皮脆香浓，需要浓醇纯米酒的丰腴口感来匹配其丰富层次，相互成就。', origin:'静冈县稻取 / 千叶县铫子', description:'金目鲷因其美丽的金色大眼而得名，体色鲜红如朱砂，是深海鱼中极具视觉冲击力的食材。寿司店通常将皮目轻炙，皮下脂肪受热融化，形成焦香与油脂并存的独特美味，是冬季寿司拼盘的压轴食材。', flavor:'浓郁甘甜，皮脂香浓，炙烤后风味更立体', texture:'皮脆肉嫩，脂肪层次分明', category:'白肉鱼', difficulty:'精深', calories:160, protein:17.8, fat:9.0, imageUrl:'', slug:'kinmedai' },
  { id:'19', name:'金枪鱼中腹', japaneseName:'ちゅうとろ / マグロ中腹', nameEn:'Bluefin Tuna Medium Fatty Belly', emoji:'🐟', gradientFrom:'#FF6B6B', gradientTo:'#FFA500', bestMonths:['4月','5月','6月','11月','12月'], tasteScore:4.7, eatingMethod:'刺身、握寿司', sakePairing:'纯米吟酿', sakeNote:'中腹脂与瘦肉比例恰到好处，纯米吟酿兼具米香与果香，能完美平衡其丰富层次，是寿司师傅最推荐的经典搭配。', origin:'青森县大间 / 长崎县对马', description:'中腹（Chutoro）是金枪鱼腹部脂肪与红肉的完美过渡地带，既有大腹的肥美油脂，又保留了赤身的红肉鲜爽。其价格适中、风味平衡，是寿司店点单率最高的金枪鱼部位，被誉为"性价比之王"。高级寿司店的中腹通常选自"蛇腹"（ハラモ）部分，脂肪纹路如大理石般细密。', flavor:'脂香与红肉鲜味并存，平衡感绝佳', texture:'柔嫩中带有适度嚼劲，脂肪层次丰富', category:'红肉鱼', difficulty:'中等', calories:278, protein:22.5, fat:20.1, imageUrl:'', slug:'chutoro' },
  { id:'20', name:'金枪鱼赤身', japaneseName:'あかみ / マグロ赤身', nameEn:'Bluefin Tuna Lean', emoji:'🐟', gradientFrom:'#DC2626', gradientTo:'#991B1B', bestMonths:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tasteScore:4.3, eatingMethod:'刺身、握寿司、铁火卷', sakePairing:'辛口纯米酒', sakeNote:'赤身鲜味纯粹浓郁，辛口纯米的干爽口感能衬托其红肉的浓郁鲜味，余味干净利落，如协奏曲般和谐。', origin:'日本各地 / 太平洋', description:'赤身（Akami）是金枪鱼背部的瘦肉部分，脂肪含量低、蛋白质丰富。虽然价格远低于大腹中腹，但优质金枪鱼的赤身同样风味深邃，经过"熟成"（エイジング）处理后鲜味更为浓缩。铁火卷（鉄火巻き）的名称来源于江户时代赌徒在赌场偷偷吃这种不散发气味的寿司。', flavor:'红肉鲜味浓郁，略带微酸，熟成后鲜味更深', texture:'紧实有弹性，肉质细腻', category:'红肉鱼', difficulty:'简单', calories:120, protein:25.3, fat:1.3, imageUrl:'', slug:'akami' },
  { id:'21', name:'牡丹虾', japaneseName:'ぼたんえび / 牡丹海老', nameEn:'Botan Shrimp', emoji:'🦐', gradientFrom:'#FF0080', gradientTo:'#FF69B4', bestMonths:['11月','12月','1月','2月'], tasteScore:4.6, eatingMethod:'握寿司（生食）、刺身', sakePairing:'大吟酿', sakeNote:'牡丹虾甘甜浓郁、口感绵密，大吟酿的花果清香能优雅地衬托其甜美，同时不掩盖其独特的海洋鲜度。', origin:'北海道鄂霍次克海 / 加拿大', description:'牡丹虾被誉为"虾中女王"，因其艳丽的粉红色泽和舒展的虾身如牡丹花盛开而得名。冬季是牡丹虾的最佳季节，此时虾头饱满、肉质甘甜，高级寿司店会特意保留虾脑供食客吸食，浓郁的鲜味令人难忘。', flavor:'极度甘甜，鲜味浓郁绵密，余韵悠长', texture:'黏糯弹牙，如奶油般丝滑', category:'虾蟹', difficulty:'简单', calories:92, protein:18.3, fat:1.2, imageUrl:'', slug:'botanebi' },
  { id:'22', name:'北极贝', japaneseName:'ほっきがい / 北寄貝', nameEn:'Surf Clam', emoji:'🐚', gradientFrom:'#EC4899', gradientTo:'#F472B6', bestMonths:['10月','11月','12月','1月'], tasteScore:4.1, eatingMethod:'握寿司（水煮）、刺身', sakePairing:'吟酿酒', sakeNote:'北极贝独特的鲜甜与爽脆口感，搭配吟酿的清爽果香，能在口腔中形成如海浪般的清爽层次感。', origin:'北海道 / 加拿大东海岸', description:'北极贝（ホッキ貝）是寿司中最经典的贝类食材之一，其艳丽的玫瑰红色源自天然的虾青素。传统江户前寿司会将北极贝微微汆烫后迅速冷却，保留贝柱的爽脆口感。北海道出产的北极贝个头更大、甜味更足。', flavor:'清甜鲜美，带淡淡海洋矿物感', texture:'爽脆弹牙，口感独特', category:'贝类', difficulty:'简单', calories:75, protein:12.8, fat:0.6, imageUrl:'', slug:'hokkigai' },
  { id:'23', name:'小肌', japaneseName:'こはだ / 小鰭', nameEn:'Spotted Sardine', emoji:'🐟', gradientFrom:'#F59E0B', gradientTo:'#D97706', bestMonths:['5月','6月','7月','8月'], tasteScore:4.4, eatingMethod:'醋腌握寿司、押寿司', sakePairing:'纯米酒', sakeNote:'小肌醋腌后的酸香与鱼鲜味融合，纯米酒的米香与乳酸风味能完美呼应，是江户前寿司最传统的搭配。', origin:'东京湾 / 三河湾', description:'小肌（コハダ）是江户前寿司的灵魂食材之一，以醋腌渍的方式完美呈现。小肌的大小对应不同名称："シンコ"（幼鱼）→"コハダ"→"ナカゾ"→"ムロ"，是寿司职人技术的试金石。高级寿司店会用多种醋按比例混合腌渍，每批鱼的盐量和醋量都需根据当天鱼的状态调整。', flavor:'醋香四溢，鲜味与酸味平衡精妙', texture:'肉质细嫩，醋腌后略带弹性', category:'青背鱼', difficulty:'精深', calories:158, protein:19.2, fat:8.1, imageUrl:'', slug:'kohada' },
  { id:'24', name:'鲍鱼', japaneseName:'あわび / 鮑', nameEn:'Abalone', emoji:'🐚', gradientFrom:'#8B5CF6', gradientTo:'#A78BFA', bestMonths:['6月','7月','8月'], tasteScore:4.8, eatingMethod:'握寿司（水煮/酒蒸）、刺身', sakePairing:'纯米大吟酿', sakeNote:'鲍鱼口感弹脆、鲜味深邃，纯米大吟酿的复杂度和余韵长度需与之匹配，才能hold住这道高级食材的气场。', origin:'北海道 / 三重县英虞湾', description:'鲍鱼被誉为"贝类之王"，是寿司食材中最为尊贵的存在。日本产的黑鲍和雌贝（メスガイ）品质最高。高级寿司店通常以酒蒸或昆布煮的方式处理，最大程度保留鲍鱼的鲜甜和弹脆口感。咀嚼时释放的浓郁鲜味，是老饕们的终极享受。', flavor:'极度鲜甜，海洋气息浓郁，余味悠长', texture:'极致弹脆，越嚼越有味道', category:'贝类', difficulty:'精深', calories:88, protein:16.5, fat:0.8, imageUrl:'', slug:'awabi' },
  { id:'25', name:'针鱼', japaneseName:'さより / 細魚', nameEn:'Japanese Halfbeak', emoji:'🐟', gradientFrom:'#60A5FA', gradientTo:'#3B82F6', bestMonths:['3月','4月','5月'], tasteScore:4.0, eatingMethod:'握寿司、刺身、昆布腌', sakePairing:'起泡清酒', sakeNote:'针鱼春季清新细嫩的口感，配起泡清酒的轻盈气泡和微酸，如春日微风般明快，是季节限定的享受。', origin:'东京湾 / 三河湾', description:'针鱼（サヨリ）是日本春季的风物诗，因细长如针而得名。春季樱花盛开时节，针鱼油脂开始积累，肉质从清瘦转为丰腴。寿司店通常以整鱼握制或切成细条，搭配生姜和葱花，清爽中蕴含丰富鲜味，是江户前寿司的季节限定美味。', flavor:'清淡鲜甜，带春鱼特有的清香', texture:'细嫩爽滑，入口即化', category:'白肉鱼', difficulty:'中等', calories:98, protein:18.6, fat:2.1, imageUrl:'', slug:'sayori' },
  { id:'26', name:'沙丁鱼', japaneseName:'いわし / 鰯', nameEn:'Japanese Sardine', emoji:'🐟', gradientFrom:'#10B981', gradientTo:'#059669', bestMonths:['9月','10月','11月'], tasteScore:4.2, eatingMethod:'炙烤握寿司、押寿司、醋腌', sakePairing:'辛口纯米酒', sakeNote:'秋沙丁脂香浓郁，辛口纯米的干爽能中和其厚重感，配以姜末和葱花，是江户前庶民美食的最佳搭配。', origin:'千叶县铫子 / 长崎县', description:'日本有谚语"鰯で頭を悩ます"（为沙丁鱼伤脑筋），形容其虽不起眼却风味绝佳。秋季的沙丁鱼脂肪最为丰厚，江户前寿司传统以"丸握り"整只握制，或以"叩き"（捶打）方式处理。价廉物美的沙丁鱼，是检验寿司职人功力的最佳食材。', flavor:'脂香浓郁，秋鰯甜味十足', texture:'柔软多汁，脂肪丰富', category:'青背鱼', difficulty:'中等', calories:217, protein:19.8, fat:13.9, imageUrl:'', slug:'iwashi' },
  { id:'27', name:'鸟贝', japaneseName:'とりがい / 鳥貝', nameEn:'Geoduck / Horse Mussel', emoji:'🐚', gradientFrom:'#F43F5E', gradientTo:'#FB7185', bestMonths:['3月','4月','5月'], tasteScore:4.3, eatingMethod:'握寿司（生食）、刺身', sakePairing:'纯米酒', sakeNote:'鸟贝脆爽鲜甜的口感，搭配纯米酒的圆润米香，能在口腔中形成鲜脆与醇厚的对比，层次感十足。', origin:'北海道 / 东北地方', description:'鸟贝（トリガイ）因其形似鸟嘴而得名，是江户前寿司中经典的生食贝类。春季的鸟贝最为肥美，贝柱粗大、甜味浓郁。寿司师傅会以极快的刀法处理，确保入口时的低温和脆度。高端寿司店的鸟贝往往来自北海道，其甜度和脆度更胜一筹。', flavor:'鲜甜爽脆，海洋气息清新', texture:'极度弹脆，嚼感十足', category:'贝类', difficulty:'中等', calories:70, protein:12.4, fat:0.5, imageUrl:'', slug:'torigai' },
  { id:'28', name:'鳕场蟹', japaneseName:'たらばがに / 鱈場蟹', nameEn:'Red King Crab', emoji:'🦀', gradientFrom:'#DC2626', gradientTo:'#B91C1C', bestMonths:['11月','12月','1月','2月'], tasteScore:4.7, eatingMethod:'握寿司、刺身、军舰卷', sakePairing:'纯米大吟酿', sakeNote:'帝王蟹鲜甜浓郁的蟹肉纤维，需要纯米大吟酿的复杂性和优雅余韵来与之对话，两者皆为顶级食材的代表。', origin:'北海道 / 俄罗斯远东', description:'鳕场蟹（タラバガニ）即帝王蟹，是冬季高级寿司的压轴食材。北海道鄂霍次克海出产的帝王蟹品质最佳，蟹腿肉饱满鲜甜，每一口都是极致享受。高级寿司店会将蟹腿肉略微加热后握制，热气带出的蟹肉香气更为浓郁。', flavor:'极度鲜甜，蟹肉纤维感明显，海洋风味浓郁', texture:'饱满弹嫩，肉质细密', category:'虾蟹', difficulty:'中等', calories:82, protein:17.6, fat:0.7, imageUrl:'', slug:'taraba' },
  { id:'29', name:'玉子烧', japaneseName:'たまごやき / 玉子焼', nameEn:'Sweet Rolled Omelet', emoji:'🍳', gradientFrom:'#FCD34D', gradientTo:'#F59E0B', bestMonths:['1月','2月','3月','4月','5月','6月','7月','8月','9月','10月','11月','12月'], tasteScore:4.1, eatingMethod:'握寿司、寿司收尾', sakePairing:'甘口清酒', sakeNote:'玉子烧的温润香甜与甘口清酒的米甜香相互呼应，是寿司套餐收尾的经典搭配，给用餐画上圆满句号。', origin:'全国（寿司店自制）', description:'玉子烧（出汁巻き玉子）是江户前寿司的"甜品"，也是衡量寿司店基本功的重要标准。高级寿司店的玉子烧以出汁、砂糖、酱油精心调味，以小火慢烤至蓬松湿润，入口如蛋糕般绵软。传统上寿司套餐的最后一贯一定是玉子烧，象征圆满收尾。', flavor:'温润香甜，含出汁鲜味', texture:'蓬松湿润，如海绵般绵软', category:'其他', difficulty:'中等', calories:150, protein:7.2, fat:8.5, imageUrl:'', slug:'tamagoyaki' },
  { id:'30', name:'鲱鱼', japaneseName:'にしん / 鰊', nameEn:'Pacific Herring', emoji:'🐟', gradientFrom:'#06B6D4', gradientTo:'#0891B2', bestMonths:['1月','2月','3月'], tasteScore:4.2, eatingMethod:'炙烤握寿司、押寿司、昆布腌', sakePairing:'浓醇纯米酒', sakeNote:'春告鲱油脂丰厚，浓醇纯米酒的厚实感能托起其浓郁风味，是北国春季的味觉象征。', origin:'北海道 / 石川县', description:'鲱鱼（ニシン）在日本北方饮食文化中占据重要地位，被称为"春告鱼"——它的到来预示着春天的临近。江户时代北海道的鲱鱼渔业繁荣一时，催生了"鰊御殿"的豪奢文化。寿司店通常以皮目炙烤或昆布腌的方式呈现，油脂丰富、风味浓郁。', flavor:'油脂丰厚，鲜味浓郁，炙烤后香气四溢', texture:'肉质饱满，皮下脂肪丰厚', category:'青背鱼', difficulty:'中等', calories:212, protein:17.8, fat:14.5, imageUrl:'', slug:'nishin' },
];

export function getFishList(): Fish[] {
  return fishData;
}

export function getFishBySlug(slug: string): Fish | null {
  return fishData.find(f => f.slug === slug) ?? null;
}

export function getSeasonalFish(month?: number): Fish[] {
  const m = month ?? new Date().getMonth() + 1;
  const label = `${m}月`;
  return fishData.filter(f => f.bestMonths.includes(label));
}
